### ISSUE TITLE
Spins forever if there is no internet connection

### ISSUE THREAD

**Issue by dobesv** [auth0/auth0-cordova#28] opened 2017-01-23 18:21 UTC
Ideally if there was no internet connection, the UI would stop and show an error like "You are not conencted to the internet.  Please check your connection and click here to try again: [Login]".  Currently it seems to just show a spinner endlessly.

**Comment by hzalaz** [comment] 2017-05-17 21:46
Closing this one since the issue is no longer valid since the library was rebuilt from scratch

**Closed by hzalaz** 2017-05-17 21:46 UTC
