### ISSUE TITLE
This needs to be updated to use Lock version 10

### ISSUE THREAD

**Issue by mikebetts** [auth0/auth0-cordova#26] opened 2016-08-09 18:52 UTC

**Comment by dobesv** [comment] 2017-01-24 02:08
Agreed, it seems to have a number of problems in Lock 10, it's not working out of the box.

**Comment by hzalaz** [comment] 2017-05-17 21:46
Closing this one since the issue is no longer valid since the library was rebuilt from scratch

**Closed by hzalaz** 2017-05-17 21:46 UTC
