### ISSUE TITLE
Native Google login

### ISSUE THREAD

**Issue by dobesv** [auth0/auth0-cordova#27] opened 2016-11-24 19:26 UTC
Currently this always uses the in-app browser for login, which means if the user is already logged in via their Android device they will have to login again.  This is ugly and not ideal since other apps will just get asked to use the account they already logged in with.

**Comment by hzalaz** [comment] 2017-05-17 21:47
Closing this one since the issue is no longer valid since the library was rebuilt from scratch. Our current approach involves the OS browser and that might mitigate some of the issues with webviews

**Closed by hzalaz** 2017-05-17 21:47 UTC
