### ISSUE TITLE
Create native Facebook + Twitter auth plugins for Cordova

### ISSUE THREAD

**Issue by mgonto** [auth0/auth0-cordova#1] opened 2014-12-30 15:18 UTC
It'd be nice if we could create some native Facebook and Twitter plugins to Login to the app just like a native one.

/cc @hzalaz

**Comment by woss** [comment] 2015-02-15 10:40
+1

**Comment by EugeneFoo** [comment] 2015-08-10 10:48
Really need this function asap, which will provide our users for more user friendly interface, instead of re-keyin the fb email and pass with the inappbrowser, thanks

**Comment by nikhilenmudi** [comment] 2016-01-04 20:13
I will start using auth0 as soon as you introduce this!!

**Comment by dorraba** [comment] 2016-02-18 13:49
Any news on this feature???

**Comment by brockmiller** [comment] 2016-03-02 00:38
+1  Really looking forward to this feature!

**Comment by hzalaz** [comment] 2017-05-17 21:47
Closing this one since the issue is no longer valid since the library was rebuilt from scratch. Our current approach involves the OS browser and that might mitigate some of the issues with webviews

**Closed by hzalaz** 2017-05-17 21:47 UTC

**Comment by virtser** [comment] 2017-10-04 10:07
@hzalaz how does it solves the mentioned problem that users can't use native Facebook app login and have to use in browser login (when most of the users not really logged in browser)?

**Comment by jebbench** [comment] 2017-10-23 11:45
This isn't working for me either; Chrome custom tabs opens but when clicking "Login with Facebook" I don't get an option to use the app - just the web site.

**Comment by webbkvalite** [comment] 2019-06-12 08:29
Is this technically doable with OAUTH? It would really lift the user experience!
