### ISSUE TITLE
We could not reach the server issue

### ISSUE THREAD

**Issue by Annyv2** [auth0/auth0-cordova#9] opened 2015-12-29 21:25 UTC
When testing Phonegap seed project, different versions of Lock had the same issue "We could not reach the server. Please try again"

For cordova-android 4 or above cordova-plugin-whitelist needs to be added to enable and restrict network access in the application.

**Comment by hzalaz** [comment] 2017-05-17 21:45
Closing this one since the issue is no longer valid since the library was rebuilt from scratch

**Closed by hzalaz** 2017-05-17 21:45 UTC
