### ISSUE TITLE
The address bar

### ISSUE THREAD

**Issue by jsguy** [auth0/auth0-cordova#17] opened 2016-03-01 22:14 UTC
Hi,

When I use this to authenticate, for example instragram via android, the location bar is shown, this looks pretty bad - are you able to allow the location bar to be hidden? I can see that it is an option in the plugin:

https://github.com/apache/cordova-plugin-inappbrowser

``` javascript
var ref = cordova.InAppBrowser.open(url, target, {
    location: "no"
});
```

Even adding it as an option that uses the current behaviour by default would be fine.

Edit: clarify that you can actually see the instagram bar, but it would still be nice to be able to configure it.

**Comment by hzalaz** [comment] 2017-05-17 21:45
Closing this one since the issue is no longer valid since the library was rebuilt from scratch

**Closed by hzalaz** 2017-05-17 21:45 UTC

**Comment by decates** [comment] 2017-05-18 10:45
Hi @hzalaz - I think this is still a valid issue/feature request in the current library. I also have a need to be able to hide the address bar, to avoid the user experience where it clearly looks like the app is opening a browser window. Can I raise a pull request for it, defaulting to the current behaviour?

**Comment by decates** [comment] 2017-05-18 10:52
Actually, scrap that - it seems that SafariViewController [doesn't support hiding the Done button and address bar](http://stackoverflow.com/questions/36612960/how-to-hide-the-done-button-and-search-bar-in-safariviewcontroller), so this is not going to happen any time soon...

**Comment by JohnMcLear** [comment] 2017-12-04 21:29
The positive (scraping the barrel somewhat) is that the user is given the confidence they are visiting the correct third party and it's not some fake login prompt..  Still, native apps can do this (hold entire window) so it's kinda sad to see Cordova can't
