### ISSUE TITLE
Inapp Browser error

### ISSUE THREAD

**Issue by Annyv2** [auth0/auth0-cordova#10] opened 2016-01-15 20:39 UTC
When testing Phonegap Native, this error was encountered

`Error: Cannot find plugin.xml for plugin 'org.apache.cordova.inappbrowser'. Please try adding it again`

**Comment by hzalaz** [comment] 2017-05-17 21:46
Closing this one since the issue is no longer valid since the library was rebuilt from scratch

**Closed by hzalaz** 2017-05-17 21:46 UTC
