### ISSUE TITLE
net: ERR_UNKNOWN_URL_SCHEME with targetSdkVersion 30

### ISSUE THREAD

**Issue by benmesza** [auth0/auth0-cordova#180] opened 2021-10-06 13:08 UTC
# Bug Report

## Problem

Use auth0 in Ionic cordova app, and when user sign in to app successfully cannot redirect to app because net: ERR_UNKNOWN_URL_SCHEME error. targetSdkVersion 29 was worked, but when upgrade to 30 get this error on Android 11 platform, but works on Android 10.

### What is expected to happen?

Successfully redirect to app on Android 11

### What does actually happen?

Get net: ERR_UNKNOWN_URL_SCHEME  error.

### Command or Code

Auth0 integration

### Environment, Platform, Device

Android 11

### Version information

Cordova CLI: 10.0.0
Cordova platform: Cordova-Android 10.1.1
Frameworks: Ionic 5 with Angular 12.1.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by brassier** [comment] 2021-11-05 19:28
Hello -
We are seeing similar issues.  Any suggestions or direction on this?
Thanks -

**Comment by cels** [comment] 2021-11-08 14:58
Hi,
same problem here as it seems.
Any ideas for a quick fix?

Unfortunately it is no longer possible to build for sdk29 since 1st of November...

**Comment by alexneats** [comment] 2021-11-10 16:37
There is a cordova-plugin-safariviewcontroller v2.0.1 (current is v2.0.0) that hasn't yet been merged that contains the fix for this issue.  In the meantime, adding this to the end of my AndroidManifest.xml gets my app around this issue:

<queries>
        <intent>
            <action android:name="android.support.customtabs.action.CustomTabsService" />
        </intent>
</queries>

**Comment by alexneats** [comment] 2021-11-10 16:44
FYI - I got the concept above from this:   https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/pull/180/files

**Comment by ciromart** [comment] 2021-11-14 11:26
@alexneats can you share you AndroidManifest ? I'm trying to put same block in my AndroidManifest, but when i run ionic cordova build android get :
Android resource linking failed
  C:\Users\ciro.martino\SmartAppCm\BarberTreatmentApp\platforms\android\app\build\intermediates\merged_manifests\debug\AndroidManifest.xml:134: AAPT: error: une

**Comment by ciromart** [comment] 2021-11-14 22:02
Ok guys i have temporarily resolved this issue before release of fixed plugin cordova-plugin-safariviewcontroller v2.0.1.

Thanks to @alexneats for suggestion.
You need to put this:
**<queries> <intent> <action android:name="android.support.customtabs.action.CustomTabsService" /> </intent> </queries>**
in AndroidManifest.xml (attention, this block must be placed outside the tag <application>).
If command **ionic cordova build android** return an error like this: **C:\Users\folder\platforms\android\app\build\intermediates\merged_manifests\debug\AndroidManifest.xml:134: AAPT: error: une** 
you probably update your gradle version to > 3.3.0 (for me 3.5.4 is ok).
**NOTE** : gradle version must be updated in build.gradle file located under path 
**platforms\android\app\build.gradle** and/or **platforms\android\build.gradle**
You probably have an error also in this case, cause is necessary update **distributionUrl** located in **gradle-wrapper.properties**.
I suggest to use almost this: 
**distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip** for gradle 3.5.4
After this changes build is ok and the problem is fixed!!!!

**Comment by AnupDhariaMariswamy** [comment] 2021-11-16 00:26
Thank you! You are awesome!

**Comment by cels** [comment] 2021-11-16 13:32
If you don't want to manually edit your `AndroidManifest.xml` (e.g. clean automated builds via some CI) you can add this to your `<platform name="android" ...` section in your `config.xml`:

```
<edit-config file="app/src/main/AndroidManifest.xml" mode="add" target="/manifest/queries" xmlns:android="http://schemas.android.com/apk/res/android">
    <intent>
        <action android:name="android.support.customtabs.action.CustomTabsService" />
    </intent>
</edit-config>
```

The plugin `cordova-custom-config` might be required, I'm not entirely sure as this is just meant as a quick note to other people struggling. :-)

**Comment by anandbhaskaran** [comment] 2021-12-08 11:26
We would love to see this fixed. For now, we are using the solution from @cels and it works well.

**Comment by vairam07** [comment] 2022-01-14 12:03
It showing an error
 {
    "original": {
        "crossDomain": true,
        "method": "POST",
        "url": "https://acredit.auth0.com/oauth/token"
    },
    "code": null,
    "description": null,
    "name": "Error"
}

**Comment by jcperuffo** [comment] 2022-02-15 17:27
Having the same problem here with Android 11 and 12 (Ionic V3, Angular 5, Cordova 10.0.0) and the solution from @cels and @ciromart worked. I did not changed the graddle classpath (mine here is 'com.android.tools.build:gradle:4.0.0').

Thank you all!

**Comment by stevehobbsdev** [comment] 2022-05-16 12:37
Thanks @cels and @ciromart - looks like a good workaround 👍🏻 I've pinned this issue for visibility.

**Closed by stevehobbsdev** 2022-05-16 12:37 UTC
