### ISSUE TITLE
onRedirectUri faulty behavior after first login

### ISSUE THREAD

**Issue by tareqdayya** [auth0/auth0-cordova#106] opened 2019-05-25 10:58 UTC
Hello,

I'm using ionic 4 along with auth0-cordova 0.3.0 and cordova 9.0.0, and i have a huge problem regarding reaching the universal login page after the 1st logout on ios. I haven't tested it on android so i can't say whether the same problem exists there.

What happens is as follows. The first time a user logs in, things go smoothly and after they're done authenticating using the universal login page, they get redirected to the app exactly as expected without any issues.

However, after they log out from the app, any attempts to login do not work. What happens is that, at first, they seem to be taken to the auth0 login page, only to be immediately redirected to a blank page with the title "Website Name." No redirection happens after that, and on clicking done, the user is back in the app without being authenticated. Hence the user is left without the ability to reach the universal login page and authenticate. Closing and opening the app does not help.

I have noticed a weird behavior regarding the onRedirectUri method. If you execute it from within a short timeout function, say 150ms, the user will not reach the universal login page, however, they will be authenticated once they return to the app. This means they can't log out and then log in using a different provider. That is not a big deal, the big deal however, is the fact that setting a timeout on the onRedirectUri method prevents 1st-time users from being redirected to the app after logging in. So, for example, if a first user is trying to log in via facebook, they will get stuck inside facebook's "you will be redirected shortly back to your app" page thinking that they still have to wait even though nothing will eventually happen and they are already authenticated and all they have to do is to click done in order to find themselves back in the app; fully authenticated.

I have tried using the ionic-plugin-deeplinks instead of the custom-url-scheme advised by auth0 but to no avail. The problem persists, and it seems that the onRedirectUri method is the culprit.

Here's the code i use to login and out inside auth.service.ts:
`const AUTH_CONFIG = {
    clientID: 'my-client-id',
    clientId:  'my-client-id',
    domain: 'my-domain.auth0.com',
    packageIdentifier: 'mybundleid',
};
    Auth0 = new auth0.WebAuth(AUTH_CONFIG);
    Client = new Auth0Cordova(AUTH_CONFIG);

constructor(
        public zone: NgZone,
        private storage: Storage,
        private router: Router,
        private platform: Platform
    ) {
       
            this.storage.get('profile').then(user => this.userProfile = user);
            this.storage.get('access_token').then(token => this.accessToken = token);
            this.storage.get('expires_at').then(exp => {
                this.loggedIn.next(Date.now() < JSON.parse(exp));
            });
        }

  login() {
        const options = {
            scope: 'openid profile email offline_access'
        };
        // Authorize login request with Auth0: open login page and get auth results
        this.Client.authorize(options, (err, authResult) => {
            if (err) {
                throw err;
            }
            // Set Access Token
            this.storage.set('access_token', authResult.accessToken);
            // Set Access Token expiration
            const expiresAt = JSON.stringify((authResult.expiresIn * 1000) + new Date().getTime());
            this.storage.set('expires_at', expiresAt);
            // Set logged in
            this.loggedIn.next(true);
            // Fetch user's profile info
            this.Auth0.client.userInfo(this.accessToken, (err, profile) => {
                if (err) {
                    throw err;
                }
                this.storage.set('profile', profile).then(val =>
                    this.zone.run(() => {
                        this.userProfile = profile;
                    })
                );
            });
        });
    }

    logout() {
        this.storage.remove('profile');
        this.storage.remove('access_token');
        this.storage.remove('expires_at');
        this.storage.remove('idToken');
        this.accessToken = null;
        this.userProfile = null;
        this.idToken = null;
        this.loggedIn.next(false);
}
`
and this is the auth0cordova code inside the bootstrapped app.component.ts. You might notice the setTimeout which i'm using at the moment cuz it seems to mitigate the problem as mentioned above:

`this.platform.ready().then(() => {
            this.statusBar.styleDefault();
            this.splashScreen.hide();
this.deeplinks.route({}).subscribe((match) => {
                    console.log(1);
                    Auth0Cordova.onRedirectUri(match.$link.url);
                }, (nomatch) => {
                    console.log(2);
                    setTimeout(() => {
                        Auth0Cordova.onRedirectUri(nomatch.$link.url);
                    }, 150);
               })
});`

**Comment by codyrushing** [comment] 2019-05-28 23:41
I am experiencing a similar issue.  After the first login, about 50% of the time, it fails to redirect back to the cordova webview.  This issue only arose after a recent build, so it could be a regression.

Using 0.3.0

**Comment by tareqdayya** [comment] 2019-05-29 07:26
i'm kinda surprised, given the popularity of ionic, that auth0 are not creating a truly cross-platform solution. If you have an app for the browser and the mobile, you need two different codes. Kinda of a bummer that the authentication is what forces you to split the code.

**Comment by fmflame** [comment] 2019-07-07 07:56
Same issue here, trying to solve it for days now. Auth0 shame on you for providing this crappy library for your customers. Not even a log out function, which i had to implement myself!

**Comment by tareqdayya** [comment] 2019-07-07 08:09
@fmflame i was able to mitigate some of the effects of the problem by using deeplinks in app.component as follows:
```
this.deeplinks.route({}).subscribe((match) => {
                    // this never happens
                    Auth0Cordova.onRedirectUri(match.$link.url);
                }, (nomatch) => {
                    Auth0Cordova.onRedirectUri(nomatch.$link.url);
                   // This is what made it work for me
                    let redirectIntv = setInterval(() => {
                        Auth0Cordova.onRedirectUri(nomatch.$link.url);
                    }, 500);
                    this.authSrvc.loggedIn.subscribe(state => {
                        if (state) {
                            setTimeout(() => {
                                // Don't forget to clear the interval after being logged in!
                                clearInterval(redirectIntv);
                            }, 2000);
                        }
                    });
                });
```
Don't ask me why, it just kinda works. And Yes, I do have developer shame for doing something without any theoretical basis.
Now, after logging out, a user should be able to log in. Sometimes, a restart of the app is necessary, but at least, they will be able to log in after restart of the app, unlike before.

This doesn't solve the other problem of not giving users an option to login using different credentials on re-login. That, should be auth0's job.

**Comment by tinysnippt** [comment] 2019-07-22 02:34
@tareqdayya This works when you login the first time. Once you log out and try to log back in, it gets stuck again.

**Comment by nitinw631** [comment] 2019-08-23 23:34
Hey any update on this issue? I am facing same problem with ionic 4 application.

**Comment by cuginoAle** [comment] 2019-10-18 18:23
Hi,
any idea on when the PR fixing this is going to be merged?

**Comment by QuantariusRay** [comment] 2019-11-14 20:47
@stevehobbsdev ^

**Comment by stevehobbsdev** [comment] 2019-12-13 11:47
Looks like the PR that fixes this has been abandoned by the author. I raised #114 to replace it with the resolved conflicts.

**Closed** 2019-12-13 11:49 UTC
